[package]
name = "xilem-chess"
version = "0.4.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
tokio = "1.48.0"
xilem = "0.4.0"
#xilem   = { git = "https://github.com/linebender/xilem.git", rev = "ac10aeb47e0ec2d9a89bcb72679d3c3445d3e4a9" }

#mpsc = "*"
#num-traits = "*"
#tokio = "1.46.1"
#tracing = "0.1.41"

[profile.dev]
opt-level = 3

[features]
salewskiChessDebug = []
