[package]
name = "xilem-chess"
version = "0.3.0"
edition = "2024"

[dependencies]
xilem = "0.4"
xilem_core = "0.4"
masonry = "0.4"
masonry_winit = "0.4"
winit = "*"

mpsc = "*"
num-traits = "*"
tokio = "1.46.1"
tracing = "0.1.41"

[profile.dev]
opt-level = 3

[features]
salewskiChessDebug = []
